# Generated by Django 4.2.1 on 2023-05-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('class_code', models.CharField(max_length=12)),
                ('course', models.CharField(choices=[('B', 'Backend'), ('F', 'Frontend'), ('D', 'Data Science')], max_length=13)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
